# username and password used for logging into the device
:credentials:               
  :username: admin
  :password: admin

#  Following UIDS are available from PXG device
#  0: 0,1,255: RM1-RPP-11A
#  2: Panel 1  -- power summary data, total information for all the breakers in panel 1;
#  3: Panel 2  -- power summary data, total information for all the breakers in panel 2;
# 18: Panel 1 (Breakers) -- individual breaker data for panel 1;
# 19: Panel 2 (Breakers) -- individual breaker data for panel 2;
# 34: Panel 1 (Standard - Odd/Even pole Data) -- EMS Panel 1 Pole Data
# 35: Panel 2 (Standard - Odd/Even Pole Data) -- EMS Panel 2 Pole Data

# Select a list of uids to download register maps for:
:uids: [ 0, 2, 3, 18, 19 ]  

# CSV file listing devices [name, ip, baseurl]
:deviceList: devices.csv    

# Directory to save files into
:targetDir: data            